### ISSUE TITLE
I still dont get what this plugin does

### ISSUE THREAD

**Issue by felixfbecker** [42Zavattas/gulp-css-url-rebase#2]
It somehow modifies urls in css files. Does it just strip `..`s from the beginning? Can I pass it a function to customize the behaviour?

**Comment by balthazar** [comment]
The examples in the readme speak for themselves I think, you may have issue when building a project and moving your assets that changes your project structure. You can see how it's used in the [Bangular](https://github.com/42Zavattas/generator-bangular) project.

No, you can't pass a function.

**Comment by olets** [comment]
Following up on that: in the readme examples, it removes all `../` from paths found in css. Is that in fact the entire behavior?
